[package]
name = "c01_lints_cargo_toml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"


