[package]
name = "cargo_sparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"

[registries.crates-io]
protocol = "sparse"
