[project]
name = "bar"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { workspace = true, features = ["unicode"]}

[build-dependencies]
cc.workspace = true

[dev-dependencies]
rand.workspace = true

